package eass.figurasgeometricas;

import java.awt.Color;
import static java.awt.Color.LIGHT_GRAY;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
public class FigurasGeometricas extends javax.swing.JFrame {
    public FigurasGeometricas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblFigura = new javax.swing.JLabel();
        lblDatos = new javax.swing.JLabel();
        btnRectangulo = new javax.swing.JButton();
        btnCirculo = new javax.swing.JButton();
        btnCuadrado = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ink Free", 3, 24)); // NOI18N
        jLabel1.setText("FIguras Geométricas");

        lblFigura.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        lblDatos.setBorder(javax.swing.BorderFactory.createLineBorder(null));

        btnRectangulo.setText("Rectángulo");
        btnRectangulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRectanguloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRectanguloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRectanguloMouseExited(evt);
            }
        });

        btnCirculo.setText("Circulo");
        btnCirculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCirculoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCirculoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCirculoMouseExited(evt);
            }
        });

        btnCuadrado.setText("Cuadrado");
        btnCuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCuadradoMouseExited(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)))
                        .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnRectangulo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                            .addComponent(btnCirculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblFigura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRectanguloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectanguloMouseEntered
        // TODO add your handling code here:
        btnRectangulo.setBackground(Color.YELLOW);
        btnRectangulo.setBorder(new LineBorder(Color.YELLOW));
        btnRectangulo.setForeground(Color.LIGHT_GRAY);
        
    }//GEN-LAST:event_btnRectanguloMouseEntered

    private void btnRectanguloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectanguloMouseExited
        // TODO add your handling code here:
        btnRectangulo.setBackground(LIGHT_GRAY);
        btnRectangulo.setBorder(new LineBorder(Color.LIGHT_GRAY));
        btnRectangulo.setForeground(Color.BLACK);
        
    }//GEN-LAST:event_btnRectanguloMouseExited

    private void btnRectanguloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRectanguloMouseClicked
        // TODO add your handling code here:
        double base,altura,area,perimetro;
        String baseMensaje,alturaMensaje;
        lblFigura.setText("Figura Rectangulo");
        baseMensaje=JOptionPane.showInputDialog("Ingresa el valor de báse");
        base=Double.parseDouble(baseMensaje);
        alturaMensaje=JOptionPane.showInputDialog("ingresa el valor de la altura");
        altura=Double.parseDouble(alturaMensaje);
        
        perimetro=(2*base)+(2*altura);
        area=base*altura;
        
        // crea un fromato solo para mostrar decimales 
        DecimalFormat df = new DecimalFormat("#.##");
        
        //Formatear Resultados
        String areaFormateada = df.format(area);
        String perimetroFormateado = df.format(perimetro);
        
        lblDatos.setText("perimetro = " + perimetroFormateado + " Área = " + areaFormateada);
        
    }//GEN-LAST:event_btnRectanguloMouseClicked

    private void btnCuadradoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseEntered
        // TODO add your handling code here:
         btnCuadrado.setBackground(Color.blue);
        btnCuadrado.setBorder(new LineBorder(Color.YELLOW));
        btnCuadrado.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnCuadradoMouseEntered

    private void btnCuadradoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseExited
        // TODO add your handling code here:
        btnCuadrado.setBackground(LIGHT_GRAY);
        btnCuadrado.setBorder(new LineBorder(Color.LIGHT_GRAY));
        btnCuadrado.setForeground(Color.BLACK);
    }//GEN-LAST:event_btnCuadradoMouseExited

    private void btnCuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCuadradoMouseClicked
        // TODO add your handling code here:
         double base,altura,area,perimetro;
        String baseMensaje,alturaMensaje;
        lblFigura.setText("Figura Cuadrado");
        baseMensaje=JOptionPane.showInputDialog("Ingresa el valor uno");
        base=Double.parseDouble(baseMensaje);
        alturaMensaje=JOptionPane.showInputDialog("ingresa el valor dos");
        altura=Double.parseDouble(alturaMensaje);
        
        perimetro=(2*base)+(2*altura);
        area=base*altura;
        
        // crea un fromato solo para mostrar decimales 
        DecimalFormat df = new DecimalFormat("#.##");
        
        //Formatear Resultados
        String areaFormateada = df.format(area);
        String perimetroFormateado = df.format(perimetro);
        
        lblDatos.setText("perimetro = " + perimetroFormateado + " Área = " + areaFormateada);
        
    }//GEN-LAST:event_btnCuadradoMouseClicked

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        // TODO add your handling code here:
       lblFigura.setText("");
        lblDatos.setText(""); 
       
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnCirculoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseEntered
        // TODO add your handling code here:
         btnCirculo.setBackground(Color.pink);
        btnCirculo.setBorder(new LineBorder(Color.YELLOW));
        btnCirculo.setForeground(Color.LIGHT_GRAY);
    }//GEN-LAST:event_btnCirculoMouseEntered

    private void btnCirculoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseExited
        // TODO add your handling code here:
        btnCirculo.setBackground(LIGHT_GRAY);
        btnCirculo.setBorder(new LineBorder(Color.LIGHT_GRAY));
        btnCirculo.setForeground(Color.BLACK);

    }//GEN-LAST:event_btnCirculoMouseExited

    private void btnCirculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCirculoMouseClicked
        // TODO add your handling code here:
         double base,altura,area,perimetro;
        String baseMensaje,alturaMensaje;
        lblFigura.setText("Figura Circlo");
        baseMensaje=JOptionPane.showInputDialog("Ingresa el valor uno");
        base=Double.parseDouble(baseMensaje);
        alturaMensaje=JOptionPane.showInputDialog("ingresa el valor dos");
        altura=Double.parseDouble(alturaMensaje);
        
        perimetro=(2*base)+(2*altura);
        area=base*altura;
        
        // crea un fromato solo para mostrar decimales 
        DecimalFormat df = new DecimalFormat("#.##");
        
        //Formatear Resultados
        String areaFormateada = df.format(area);
        String perimetroFormateado = df.format(perimetro);
        
        lblDatos.setText("perimetro = " + perimetroFormateado + " Área = " + areaFormateada);
        
    }//GEN-LAST:event_btnCirculoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FigurasGeometricas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FigurasGeometricas().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCirculo;
    private javax.swing.JButton btnCuadrado;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRectangulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDatos;
    private javax.swing.JLabel lblFigura;
    // End of variables declaration//GEN-END:variables
}
